name: Build APK Flutter

on:
  workflow_dispatch:
  push:
    paths:
      - "flutter_ecostay_app.zip"
      - ".github/workflows/build-apk.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil repository
        uses: actions/checkout@v4

      - name: Siapkan ZIP
        run: |
          mkdir project
          unzip flutter_ecostay_app.zip -d project

      - name: Cari project Flutter
        run: |
          echo "Mencari pubspec.yaml..."
          find project -name pubspec.yaml

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependency dan build APK
        run: |
          PROJECT_DIR=$(dirname "$(find project -name pubspec.yaml -print -quit)")
          echo "Project ditemukan di: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          flutter pub get
          flutter build apk --release

      - name: Simpan APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-ecostay-apk
          path: project/**/build/app/outputs/flutter-apk/app-release.apk
